---
- hosts: nodes

  tasks:
    - name: Root Password (ALL)
      user: name=root    password="$5$PK7KM9pT$AehNIMYtW22TEE.D0U3ORWCDFMFvARwJLf8YPvVgAf."

    - name: Student Password (ALL)
      user: name=student password="$5$OJx9uJm8$4VYM2llNxqX/7I4M3vXZM8ZJ9FE2msmHpcOqXlDesC8"

    - name: YUM installation of misc required packages
      yum: name=wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct state=installed

    - name: YUM installation of docker-1.13.1
      yum: name=docker version=1.13.1 state=installed

    - name: SERVICE state of dockerd
      service: name=docker state=started enabled=yes
