---
- hosts: nodes
  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:




- hosts: masters
  tasks:
  
    - name: "YUM install httpd-utils"
      yum: name=httpd-tools state=installed




- hosts: nodes
  tasks:
  
    - name: "USER root password reset"
      user: name=root    password="$5$PK7KM9pT$AehNIMYtW22TEE.D0U3ORWCDFMFvARwJLf8YPvVgAf."

    - name: "USER student password reset"
      user: name=student password="$5$OJx9uJm8$4VYM2llNxqX/7I4M3vXZM8ZJ9FE2msmHpcOqXlDesC8"

    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644


    - name: "YUM install misc required packages"
      yum: name=wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct,firewalld state=installed

    - name: "SERVICE STOP firewalld"
      service: name=firewalld state=stopped enabled=yes

    - name: "CMD flushing any existing iptable rules"
      shell: 
        cmd: |
          iptables -F

    - name: "SERVICE START firewalld"
      service: name=firewalld state=started enabled=yes

    - name: "YUM install docker-1.13.1"
      yum: name=docker-1.13.1 state=installed

    - name: "SERVICE STOP docker"
      service: name=docker state=stopped enabled=yes

    - name: "TEMPLATE install /etc/sysconf/docker-storage-setup"
      template:
        src: docker-storage-setup
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: "CMD clean up any pre-existing docker-storage config and execute docker-storage-setup"
      shell: 
        cmd: |
          rm -f /etc/sysconfig/docker-storage
          rm -rf /var/lib/docker
          vgs docker-vg && vgremove --force docker-vg
          pvs /dev/vdb1 && pvremove --force /dev/vdb1
          wipefs -a /dev/vdb
          docker-storage-setup

    - name: "SERVICE START docker"
      service: name=docker state=started enabled=yes
      
