---
- hosts: workstation
  tasks:
  
    - name: YUM installation of misc required packages
      yum: name=wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct state=installed

    - name: YUM installation of atomic-openshift-{utils,clients}
      yum: name=atomic-openshift-utils,atomic-openshift-clients state=installed




- hosts: masters
  tasks:
    - name: YUM installation of httpd-utils
      yum: name=httpd-tools state=installed




- hosts: nodes
  tasks:
    - name: Root Password (ALL)
      user: name=root    password="$5$PK7KM9pT$AehNIMYtW22TEE.D0U3ORWCDFMFvARwJLf8YPvVgAf."

    - name: Student Password (ALL)
      user: name=student password="$5$OJx9uJm8$4VYM2llNxqX/7I4M3vXZM8ZJ9FE2msmHpcOqXlDesC8"

    - name: YUM installation of misc required packages
      yum: name=wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct state=installed

    - name: YUM installation of docker-1.13.1
      yum: name=docker-1.13.1 state=installed

#    - name: Configuring docker-novolume-plugin in /etc/sysconfig/docker
#      template:
#        src: ~/OCP-Workshop/configs/docker
#        dest: /etc/sysconfig/docker
#        owner: root
#       group: root
#        mode: 0644
#
#    - name: YUM installation of docker-novolume-plugin
#      yum: name=docker-novolume-plugin state=installed

    - name: Configuring docker storage in /etc/sysconf/docker-storage-setup
      template:
        src: ~/OCP-Workshop/configs/docker-storage-setup
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: Stopping dockerd services before configuring docker-storage
      service: name=docker state=stopped enabled=yes

    - name: Cleaning up existing config and executing docker-storage-setup
      shell: 
        cmd: |
          rm -f /etc/sysconfig/docker-storage
          rm -rf /var/lib/docker
          vgs docker-vg && vgremove --force docker-vg
          pvs /dev/vdb1 && pvremove --force /dev/vdb1
          wipefs -a /dev/vdb
          docker-storage-setup

    - name: Starting service docker-novolume-plugin
      service: name=docker-novolume-plugin state=started enabled=yes

    - name: Starting service dockerd
      service: name=docker state=started enabled=yes
      
