##
## Moved "workstation" tasks into separate playbook to avoid having a package install/upgrade affect
## a addtional ansible tasks (ie: it potentially breaks the next task execution)
##

- hosts: workstation
  tasks:
  
    - name: "YUM install misc required packages"
      yum: name=wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct state=installed

    - name: "YUM install atomic-openshift-{utils,clients}"
      yum: name=atomic-openshift-utils,atomic-openshift-clients state=installed
